site_name: Zenvrm Docs
site_url: https://devzvrm.github.io/zenvrm-docs
dev_addr: 127.0.0.1:8100
theme: 
    name: material
    features:
    palette:
        - scheme: default
          primary: teal
          toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
        - scheme: slate
          primary: cyan
          toggle:
                icon: material/toggle-switch
                name: Switch to light mode
nav:
    - Home: index.md
    - About: about.md
    - Upcoming Features: upcoming-features.md
    - Smart Home Integrations:
      - Controllers:
        - home-controllers/index.md
        - Ezlo: home-controllers/ezlo.md
        - Vera: home-controllers/vera.md
      - Ecobee: thermostats/ecobee.md
    - Support: support.md

